### ISSUE TITLE
Update to remap-istanbul 0.8

### ISSUE THREAD

**Issue by MichaReiser** [sshev/karma-remap-coverage#10]
Please update to remap-istanbul 0.8 so that the new features can be used.

Thanks,
Micha

**Comment by sshev** [comment]
@MichaReiser Thanks for informing! Updated here https://github.com/sshev/karma-remap-coverage/commit/553865cd837308829606e0ccb8e9eb0ea9885357 and published to `npm`

**Comment by MichaReiser** [comment]
Thanks!
